name: Update Publications
on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install scholarly

      - name: Fetch Publications
        run: python fetch_scholar.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          
          # Set the remote URL to use the personal access token
          git remote set-url origin https://JimAchterbergLUMC:${{ secrets.GH_PAT }}@github.com/JimAchterbergLUMC/JimAchterbergLUMC.github.io.git
          
          git add publications.json
          git commit -m "Updated publications.json from Google Scholar" || exit 0
          git push origin main
