name: Update Publications
on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday
  workflow_dispatch:  # Allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install scholarly

      - name: Fetch Publications
        run: python fetch_scholar.py

      - name: Commit & Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add publications.json
          git commit -m 'Update publications' || exit 0
          git push
